language: android
sudo: required
jdk: oraclejdk8
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
env:
  global:
  - ANDROID_API=24
  - EMULATOR_API=21
  - ANDROID_BUILD_TOOLS=24.0.2
  - ADB_INSTALL_TIMEOUT=5
  - secure: cjOA92q6WgrvatDABJI26ytkbKh1wrML2xIfFou2cgGSotW3R1I5taTJqbhNKXhr0ctiomd3N3hYFhUJilv27b8ft2XjsA1hJhrDH1uHiubQ+/xVn7l2DLs9NdgJacmJBqIvMoJsJVHugHLxdzZ0d/0YG3bTAqsy8Zda4cTv6fTSE1Y4g0MDM3Gh/g/LkAX5M/UNmhXwL4fKInWfvXYplkZ4yG5FMXnd5zdXWoYKhTT1LSXWYeII9/YPGBj40qCPiyJsLY0eOhXs/+Vt8S4PeQPu46uQHkZJM2oOGYSa7Kv9aUYDLKD3ybsJsXH/dx0HsgLbxPhDOrRVKf0jtDyOldDWRcJI10z8VuQNpsd1V6NgNcsvESYimAONAwqMyjNNy8z6Ujbr96NOVw0P5Fu/MiZqO0HBD/3zdB4272evyH2TSexzEKrlBqniNc6SVjUCpUpkOe1PckS1HYy73b8FWZ7RmfahQowIK771rr8kA7GeMkfHT8+pMwjoR0NDDBH4Y5IJQtrTDFQGI3i1hzLNvcxbBxI0It0vp6Kz7Ju8Osfif4drIOvl7fA9uMtbfypThSkKd1Qz2NaFKVmd2b4un+8WfYRD/53WoDI8976W6W4SLNJxUqrEGYErCDaW1dir97DRvxvVwyExhKGsus36XR6uiaPT5xYMiQwG1GEgCqA=
  - secure: XpNMdJOkIBQ28Y95bIxJkBhdoWq3RcS01R+qAlSYa7DGfhDbzSk6sa13VBhVqsDFBWewrKmf/r/e99VAkha9Fv2sj8alUUiDPY3MswM6INoOCM75hD+HSb8WYp/iTCdc++DgPS9YwAc4f8/6NHtz9aHZQs+qyAUB/o5VH9X3z520iwA4KGs7WBBkCF3jPHG/IBejhA/lmxKIhbP6svz4K3k2/lFO69JRgTukYGnL0elgUCU/PnyyJxCBFcy9ey0HHDHdvyNFrKphxOS2GpsCEPGaTlAN9mGIeakKFSPNLEEEP2La7z+CLdVHaP94mlmheVHusqiNjvGT/YBgPnBcAIfkxW5caFD9EHv+AljhJ27KCjCSoX+ShU5JX55SmyKnHSTl5cjWh+S4XBfwW/xctegP/yJqop6+nsbFpFnGuk5Tq/8yox/zMyq1qdEIIZ6I7ZfGrUUWheZ0sdsv0aRpWgp8PSIInHjpXOaTAEvJV1wUNwS1obfaUctqMXzIktkumU91jQdW0awNJNQKOH9bxkTc8sjbpx/tvC2MCqjzTdtKAZtjirf+J07M0AG0ocCkPBwXaRNeGkBoWcUJOTYeNQAS05D2VchT9N8DO07iiR/hD5iEVaYE7qamwubJswu8Ky0wlQKsbI+BKF79oMJ99LtA/+l/QQdBxdbU69znrAU=
  - secure: embRkkec6euGVJDni/4Z4Yg+Gjvgi4VqGzE08sk6qpoNbr/Z31Eqbq1jKHvJQAsssXRWWWpnHn3HOzPe2q1USQdgrao1yVNh+l4YlY5TJuV1vcz85y4uB5Z+iXxXJiCsXBLSJiAKq1KxvTGe2xu1ptr6weJDP21Tn+H7LDMJyG1LaWbDPQyMUb0pvjRduS/0F4sWJqxjupzJmvWHwyJB4V/XfnszL1fEBIQhrm5xyM0yYoZUkjTfmM249frhgoQJGE3O1QAS4ticxy+IL2unkDny63IXxzUA5FYZThlTdxaQLWRV0iriDoRx9TS/P93brWgOrrukHc6eBhhYmyC/mhOKyx9DEZEWidrKPrv/Mg26GUAzmq4523jYQRawXQljj9vC/o1ltAcNb/7dWv5uBT4e6j92Y+DMELrw+YPvqDsl9UScnQQRHDBh1eDPLO8kh+YtnE5e2d6tSltK7f+gz2wv0vEjqhlvXzZ+/+k7xJZWAm5fTKm1qTe3ftp9i3/5KIIeVe8PVhLB78ShkbvsP0eMg42Lo1EcYy4Vl5YVxHR23GD903GGMr0BMzwU481TV3BPGZI/W+jcZml5abW06pXm/DPN2cCGL5iFHSpVkgSySb3lxbbBCd5IHPf9ITc+02PUzzEzKq8JG0xrkE1EfC13C2g/rzmjydWf8ADkkhE=
  - secure: 3QdGzrK+yE0smDraCQV/4aDXYr4Y+dz2QgBFHn0uzq7vclKJLcAO9Qq4foyHfOdOyQKwHrNLBRr2H3qopmWmWjmj2mhEuLmsglrzxBDMtEgjyGjgSy0QvLHafNfR/nj4P5ddEEMXimaTp8InIUF3K49AG6v2VNJS1dXtv/ZVvWlDuTUsA5yiiQf1JX5aYF0hI5M/cblUC66ehWvsUfObj9GLRcvIl2xcX0QLbGvrhnpBIascd9ULZahEfQhijd3hC9VHu9hM+YHvLHM4KE9h13n41hTKndofDQggG4HVPAFCV5ngDzlifGoZmoma0XGfmBMgJOwQkLT9l6YICpGGN8ebLlC2zC4yZZvE/bPKoh8e3rRzbQjiPJqW16nKx1/k5viKdgjAAiiWXoWY2QHv2QII2l9Dxs4Xh9Sc+qOA6LYBaZeNOKkNp+Ux1mfVM8rFm8N5BvH7LPLQO0Ru0Ty5Esb21qbRU1urj4OInZMjGEoUJl4IWCpiy0btboGCHTnuvX8ot0VDvSvG8dgk5PPg7MsiRFz3WyD3iP4QIxK8SaXMzI4E2IP6HN8nZI2cwyjisIojQxrOxYM7X8yoJSBo2rKouSO5Qn7gMKLYnWu6wohB+1aPqSwNR30NnE+tXP+2OVqbdUTHTrFnb2jJ/2pf4M9TPWw8tlGwRZ/1IMsQzaA=
  - secure: zNtIaEcxzVYac7Di+6zR90zbKRAy1tQtOrW2GyHXH1LRiP7FemH3vvtJfSs7NT0dMSLYmRJD9YNKRumN+8tABvt2i8zFr+liUl5A+vp484Nsn7AKn2gf5B8IR7TNLp8DTdvHsx3iR8yyM/HWVJjSXmE7xAMmMqh4kPmGIUKCuiKlmFYze5vF0imtNjYU4Q3PeEb/4HsQC/qE8fchy1VNU15ywgDBhxNhb/MIGHwEkjOwLHnK7Nu6fINBheMjcoTkePQRrMY4XoABSzNrZoSshjJhRv2E0G77+CnEfVzH/9rzCx0ANlRLNNVnfYSzRVeAJigrfzABEhGvWnftYLBtlKYj3hRiDJZo822Hh2vyRoZTFyeAZTXGU2iW3176wwbDTNC9q84cMizqXt4D0hx8rnzdDm+KshCOddi1PXrZg/GXbngYq4/arszs8Vo6Z+Wha2yeaw6D/PcocQQWelBkrVKP7cYDpiR7fYOw1ZtH1OxnY3rTOmp718kavwO7CkFa/ni8r6ws1QkVLhfmMBSWcVhi8TQX2j48d5w04oWK0ea0B75yBidDNmRprU0g0jcscs6N2DsN3uX6wFQBFgGpyTXvV2NY9Rgolr1nMzPF/iQA53dcW0YxR4sSsOOR+MVylUw/pzplSGn8gw2cAcNR4jxU3A+4RJEUoDa5JQT6dWM=
  - secure: vvSWBsTsQN0MWsiyUR83zhCg2v7cZUHFywF2aJSCszGUxHpQb/cXWT+p2zfBHro445RSXTFA+lxKYwoupH2HHgeUsT8wSMLXr2xZetmf8i/puTxb1v0Lzjso7LwocPJTvsWbOg2jKdIctoq9XGGgSA1AMbo1oq5MWOe4l14EY1LJss3giL1338XQK96JoRLtDPSz7l0UASxyZWadtQWFLfIw3iY7UlDafu0SmlRRLvJVVv/NDL4QioXs/l2xieB2/MwDjsBIB+L2uOVOBSohYGTFMJ+UApj0AHiqlPMOvt2u23qClbfbGWnRZPJ6Jmd5pFMtd4LEGy1WAkm2TSWMTrdMr96CBvduz4/Cc/d1uBYmDa6Ssrk8MkhcC2MwTzH5WVvsXAsAcnnmF/SBjRN7qaWgHAzAfDqGteKHEtm8DdE10MTkj9wHmtzT6r3Utymvi42P1dkn8o+hMU7SkKsdRAgc/WH+NKUaY0Juc9+s5Zoep46P/drXHn9Z1oAmkFTGm37jX3e0oJeIWMQw+Mhp+cPl8EBJgxaOOBW3U0w6oHamB8QvDgOSCV/GiHQ5XvXKZDjEQ1txii9JH9iNMTZUqye9Fw7umbo5yj5+gChDw6ek0q2j4DXN0iANPjQjVyusL1TyFAXznYLZO2PdCeH84i9xYUkCoH0fjZmJU10Rdy8=
  - secure: Rx0UgigZRmWpMNUVByjxQTYyUQn6uDISu5dtD3tvNdeyRdeNjJF9v4WjJxBXWOo3weiR6WUZ/VrpJ0xC0S2/CnhuS7TvTXq3IZn6qgBALag0GxpdnuFkNd21IYPhsv8O8UdyGXI3RhLsfmXrnACNJG/ODXTfaNzy4eeuLYLXMgrtZ0CT5UKa06g5xjIhHJPxBEmsGgDuOVNRWMEMZrN4sZ0NddvPlg/0JZ/zL2kB0N3iU+CpqfDX3lqPSxy2DXlm8vLPQAUwXwV4tM3XF1l8l8HSVzKRKgOC3PvE9AQi7WVwz5Cv6okF2S9Vv1CunTl23pcaBKErkMWssnby80niUZfY4QGfDYL0cc2d088U4iIg40EVtbGojNRH9fFSW5VJ7uIZyxR+qumV7L3gM6NkXiWWzDpYbYOo+eXllRJLR5tJusBxvpPBIg3us90oNJTfUKJik80bzrHmAfxPpMr2Zmaxax5keKiq2usJF79GaNp3zaYCPr+VIO/n7QFCQFJorLy1ff+3fnxlOsrjH9EtdAujkWNRfwfD9bgo7oqvtocJ9DKNGIEDOK2aagcxBphNz8i145sIxJAxRtCP9OSgM8tlxHLgyh8Fr9oQGjlwOtLb5jGVjt+OsKX2E3ruO9Eg9+JDpZp3e7V3Xg768I3hX6tM9PMaoHjz42fmxsJVja4=
android:
  components:
  - tools
  - platform-tools
  - build-tools-$ANDROID_BUILD_TOOLS
  - android-$ANDROID_API
  - android-$EMULATOR_API_LEVEL
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-19
  - sys-img-armeabi-v7a-addon-google_apis-google-$ANDROID_API_LEVEL
  - sys-img-armeabi-v7a-addon-google_apis-google-$EMULATOR_API_LEVEL
  - build-tools-27.0.3
  - android-26
  - android-25
  - android-24
  - android-23
  - android-22
  - sys-img-armeabi-v7a-android-22
  - extra-android-support
  - extra-android-m2repository
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
before_install:
- openssl aes-256-cbc -K $encrypted_aaf4a3063d98_key -iv $encrypted_aaf4a3063d98_iv
  -in my_planet.enc -out my_planet -d
- mkdir "$ANDROID_HOME/licenses" || true
- chmod +x gradlew - yes | sdkmanager "platforms;android-28"
- "./gradlew dependencies || true"
install:
- echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
- echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"
- echo y | android update sdk -u -a -t tools
- echo y | android update sdk -u -a -t platform-tools
- echo y | android update sdk -u -a -t build-tools-27.0.1
- echo y | android update sdk -u -a -t android-27
- echo y | android update sdk -u -a -t extra-google-m2repository
- echo y | android update sdk -u -a -t extra-android-m2repository
before_script:
- echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
- emulator -avd test -no-skin -no-audio -no-window &
- android-wait-for-emulator
- adb shell input keyevent 82 &
script:
- "./gradlew clean build connectedCheck -PdisablePreDex --stacktrace"
before_deploy:
- cp $TRAVIS_BUILD_DIR/my_planet $HOME
- cd app/build/outputs/apk/
# - jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore $HOME/my_planet -storepass 'oleoleole' -keypass 'oleoleole' app-release-unsigned.apk my_planet
# Verification
# - jarsigner -verify app-release-unsigned.apk
- "${ANDROID_HOME}/build-tools/24.0.2/zipalign -v 4 app-release-unsigned.apk myPlanet.apk"
deploy:
  provider: releases
  file: app/build/outputs/apk/*
  skip_cleanup: true
  on:
    repo: open-learning-exchange/myplanet
    tags: true
    jdk: oraclejdk8
  api_key:
    - secure: rsZw8MbCWO+Omm/X2Lk4Fs1lrWnDgDPLdVbt5mlMyNSd6SQfOVgtqy7xG2Q/kFLvAeOYaOeBC5xwWTFYzJ3FHXVwZsimuBVFml8/dmDV0qFOUgj/9aIjiB65c/kXDwoPUnU8fuvxT62HbTneAcofmTluccNfF9CXcmtbUgrpxm4naLEUGm0+0jkTsP1NQoKdIOFRaDEoPqYR7QBgv9IvsZJqZNwfxrOGsWSnmsjsbdwQawRGhRhshIjovK7xrVgZmsiovBYQand6+I8LtgZMNSRR1FgwZF1kiyfi7VTQdQFqLLhyEW5C2nu/1NxaAucwiQ3sL3bRSgvFIFe7DPU18bV/MiGWaBmGXt4rucWKEQjDG8X2w1qpexoNjGg88+KFnqVk0Mw4KvlmkFjbn5zRN7hZtuAavlABlQ/5DH6CC2y/KQyUi/e2Gh8Y71HbHbTUjufF+dR9eutcta8Jsqs8l2nYuxY7BvT1pqGbVwsgWudLNIOL1WoqpUn24lSzX4r2a76XQwhh5IBA03qfdoLEQ4lxJci1qI5lDY+LQhVYdHwRg8frwwLDc/Z8/vGHRikkxYDF//PzZJrXCe6UBq/JwWcdD3dyEeSYdbuCevNUIMF5+psEzALPJN3dwJ5jBQDKpyrLAxzCYZMdnDErWH0OaTqzauwnNNWNe8iWANRApGw=
    - secure: EDZAa1awpvW6TrPatpIryndtYneow8usz4bLpjPFGJu3ZxSXWtHHfC49FfRdGSYkEbTzQia95vTrzDk9z45wn1uX4QhhRX17f9HzDrWwNEc4K7SSWpU491K9cgzTW+hJ/S2sa0Ezcfo0Bb1MUFV0bVIaizgRQPKVt5eMHyQCdbPq87qafqWM37kSpI7NcGNqgUU5Ctb8E1GaYyPQlT8RddZrby5Uld1mOlk+0bkmuRWBDHfQRXLMeCileKZDUA2o4rtnoixZijAfaI0DOIyNM75ib3K9jiQFMMmAkFju5KF3PbvLACfn5dXNRDzMHkuNX1bnvwE5DRpKeBHi/NI5DnnNFp+S80e8evVTaht0hdec5nFpgxVYnswg2fUcRyYSKVdA7W8pqgiumvj3iETS6MWccZg0P2prla5+7h61i6StaJkqK8kY5qSwNlLefDvFqxH4ij16PPsaRDvUYteEA5oANZ/tCy9/78qGrvE9dBajwoaKfH3vEQE5aKadNoEWR1urWX4kiwvk0NlxduuHIvRkSFJK+mUO85S7e/bA0U/BxmbyjdOCHSggh3n5t2YmOF1QcHk3prHG1s0ZEOOivL1j0DCTJ6yHGsgd+BRhNWTOK7goABzJHFWyQXtDTfzs3aUA4ItbLTXgRQ9JqI9SvW9udkIW6dUqtVDHkEVXUbc=
after_success:
    - sh scripts/tag.sh
