name: myPlanet build test

on:
  push:
    branches:
      - '*'
      - '!master'
#  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build: [default, lite]
    env:
      ANDROID_NDK_VERSION: "21.3.6528147"
      BUILD_TOOLS_VERSION: "30.0.2"

    steps:
      - uses: actions/checkout@v4
      - name: diff the code to get lite
        run: |
          if [[ "${{ matrix.build }}" == "lite" ]]; then
            echo "lite"
            ls -al \
              app/build.gradle \
              app/src/main/AndroidManifest.xml \
              app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt \
              app/src/main/java/org/ole/planet/myplanet/base/PermissionActivity.java \
              app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.java
            sed -i 's/\(versionName "[0-9.]\+\)"/\1-lite"/' app/build.gradle
            cp app/src/main/AndroidManifest.xml.lite app/src/main/AndroidManifest.xml
            cp app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt.lite app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt
            cp app/src/main/java/org/ole/planet/myplanet/base/PermissionActivity.java.lite app/src/main/java/org/ole/planet/myplanet/base/PermissionActivity.java
            cp app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.java.lite app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.java
          fi
      - name: setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'
      - name: install NDK
        run: |
          echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;${ANDROID_NDK_VERSION}" --sdk_root=${ANDROID_SDK_ROOT}
          chmod +x ./gradlew
      - name: build debug as test
        run: ./gradlew assembleDebug
