name: myPlanet build test

on:
  push:
    branches:
      - '*'
      - '!master'
#  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build: [default, lite]
    env:
      ANDROID_NDK_VERSION: "21.3.6528147"
      BUILD_TOOLS_VERSION: "34.0.0"

    steps:
      - uses: actions/checkout@v4
      - name: ensure lite files also updated
        run: |
          git fetch origin master
          files=(
            "app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt"
            "app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt.lite"
            "app/src/main/java/org/ole/planet/myplanet/base/PermissionActivity.kt"
            "app/src/main/java/org/ole/planet/myplanet/base/PermissionActivity.kt.lite"
            "app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt"
            "app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt.lite")

          any_changes=false

          check_file_pair() {
            local file1=$1
            local file2=$2

            # Check if either file has been modified in the commit range
            if git diff --name-only HEAD origin/master | grep -E "^($file1|$file2)$" > /dev/null; then
              any_changes=true
              if ! git diff --name-only HEAD origin/master | grep -E "^($file1)$" > /dev/null ||
                 ! git diff --name-only HEAD origin/master | grep -E "^($file2)$" > /dev/null; then
                errors+=("Error: Both $file1 and $file2 must be changed together.")
              fi
            fi
          }

          for ((i=0; i<${#files[@]}; i+=2)); do
            check_file_pair "${files[i]}" "${files[i+1]}"
          done

          if [ ${#errors[@]} -gt 0 ]; then
            for error in "${errors[@]}"; do
              echo "$error"
            done
            exit 1
          fi

          if [ "$any_changes" = true ]; then
            echo "All file pairs have changes."
          fi
      - name: diff the code to get lite
        run: |
          if [[ "${{ matrix.build }}" == "lite" ]]; then
            echo "lite"
            ls -al \
              app/build.gradle \
              app/src/main/AndroidManifest.xml \
              app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt \
              app/src/main/java/org/ole/planet/myplanet/base/PermissionActivity.kt \
              app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt
            sed -i 's/\(versionName "[0-9.]\+\)"/\1-lite"/' app/build.gradle
            cp app/src/main/AndroidManifest.xml.lite app/src/main/AndroidManifest.xml
            cp app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt.lite app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt
            cp app/src/main/java/org/ole/planet/myplanet/base/PermissionActivity.kt.lite app/src/main/java/org/ole/planet/myplanet/base/PermissionActivity.kt
            cp app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt.lite app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt
          fi
      - name: setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'
      - name: install NDK
        run: |
          set -x
          echo "ANDROID_HOME is set to: ${ANDROID_HOME}"
          echo "ANDROID_SDK_ROOT is set to: ${ANDROID_SDK_ROOT}"
          echo "ANDROID_NDK_VERSION is set to: ${ANDROID_NDK_VERSION}"
          echo "y" | sudo ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --install "ndk;${ANDROID_NDK_VERSION}" --sdk_root=${ANDROID_SDK_ROOT} 2>&1
          if [ $? -ne 0 ]; then
              echo "SDK Manager command failed"
              exit 1
          fi
          set +x
          chmod +x ./gradlew
      - name: build debug as test
        run: ./gradlew assembleDebug
