name: Android Check CI

on:
  push:
    branches:
      - '*'
      - '!master'

#on:
#  workflow_dispatch:
#    inputs:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'
      - name: Install Android NDK and Make Gradle Wrapper Executable
        run: |
          echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;${ANDROID_NDK_VERSION}" --sdk_root=${ANDROID_SDK_ROOT}
          chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew assembleDebug
