name: myPlanet build test

on:
  push:
    branches:
      - '*'
      - '!master'
#  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build: [default, lite]
    env:
      ANDROID_NDK_VERSION: "21.3.6528147"
      BUILD_TOOLS_VERSION: "34.0.0"

    steps:
      - name: checkout repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: check for .lite diffs
        if: matrix.build == 'lite'
        run: |
          files=(
            "app/src/main/AndroidManifest.xml"
            "app/src/main/java/org/ole/planet/myplanet/base/PermissionActivity.kt"
            "app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt"
            "app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt"
          )
          for file in "${files[@]}"; do
            echo "$file .lite"
            ls -al "$file"
            ls -al "$file.lite"
            diff "$file" "$file.lite" || true
            echo "next"
          done

      - name: diff the code to get lite
        if: matrix.build == 'lite'
        run: |
          echo "lite"
          ls -al \
            app/build.gradle \
            app/src/main/AndroidManifest.xml \
            app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt \
            app/src/main/java/org/ole/planet/myplanet/base/PermissionActivity.kt \
            app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt
          sed -i 's/\(versionName "[0-9.]\+\)"/\1-lite"/' app/build.gradle
          cp app/src/main/AndroidManifest.xml.lite app/src/main/AndroidManifest.xml
          cp app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt.lite app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt
          cp app/src/main/java/org/ole/planet/myplanet/base/PermissionActivity.kt.lite app/src/main/java/org/ole/planet/myplanet/base/PermissionActivity.kt
          cp app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt.lite app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt

      - name: setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'
          check-latest: true

      - name: cache gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: cache NDK
        id: cache-ndk
        uses: actions/cache@v4
        with:
          path: ${{ runner.tool_cache }}/android-sdk/ndk/${{ env.ANDROID_NDK_VERSION }}
          key: ${{ runner.os }}-ndk-${{ env.ANDROID_NDK_VERSION }}
          restore-keys: |
            ${{ runner.os }}-ndk-

      - name: install NDK
        if: steps.cache-ndk.outputs.cache-hit != 'true'
        run: |
          set -x
          echo "ANDROID_HOME is set to: ${ANDROID_HOME}"
          echo "ANDROID_SDK_ROOT is set to: ${ANDROID_SDK_ROOT}"
          echo "ANDROID_NDK_VERSION is set to: ${ANDROID_NDK_VERSION}"
          echo "y" | sudo ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --install "ndk;${ANDROID_NDK_VERSION}" --sdk_root=${ANDROID_SDK_ROOT} 2>&1
          if [ $? -ne 0 ]; then
              echo "SDK Manager command failed"
              exit 1
          fi
          set +x
          chmod +x ./gradlew

      - name: verify NDK
        run: |
          ls -al ${{ runner.tool_cache }}/android/ndk/${{ env.ANDROID_NDK_VERSION }}

      - name: build debug as test
        run: |
          ./gradlew assembleDebug
