name: myPlanet release

on: 
  push:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  release:
    name: myPlanet release
    runs-on: ubuntu-latest

    env:
      ANDROID_NDK_VERSION: "21.3.6528147"
      BUILD_TOOLS_VERSION: "30.0.2"

    steps:
      - name: checkout repository code
        uses: actions/checkout@v3

      - name: expose version from build.gradle
        uses: dogi/expose-android-build.gradle-version-code-and-name@v1.0.1
        with:
          expose-version-name: 'true'
          expose-version-code: 'true'

      - name: setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: install NDK
        run: |
          echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;${ANDROID_NDK_VERSION}" --sdk_root=${ANDROID_SDK_ROOT}
          chmod +x ./gradlew

      - name: build debug and release APK
        run: |
          ./gradlew build
          ls -alR app/build/outputs/apk

      - name: build release AAB
        run: |
          ./gradlew bundleRelease
          ls -alR app/build/outputs/bundle
          mkdir -p output
          cp app/build/outputs/apk/debug/m* output/

#      - name: sign release APK
#        uses: Tlaster/android-sign@v1.2.2
#        with:
#          releaseDirectory: app/build/outputs/apk/release
#          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
#          output: output
#          alias: ${{ secrets.ALIAS }}
#          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
#          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: sign release APK
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: sign release AAB
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: copy builds to directory and generate sha256
        run: |
          cp app/build/outputs/bundle/release/app-release.aab output/myPlanet.aab
          cp app/build/outputs/bundle/release/m*.apk output/myPlanet.apk
          cd output
          sha256sum myPlanet.apk > myPlanet.apk.sha256
          sha256sum myPlanet.aab > myPlanet.aab.sha256
          cd -
          ls -alR output

      - name: publish to playstore
        uses: r0adkll/upload-google-play@v1.1.1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: org.ole.planet.myplanet
          releaseFiles: output/myPlanet.aab
          track: internal
          releaseName: "${{ env.ANDROID_VERSION_CODE }} (${{ env.ANDROID_VERSION_NAME }})"
          #changesNotSentForReview: true
          status: completed

      - name: rename APK/AAB with version and branch for artifact
        if: github.ref != 'refs/heads/master'
        run: |
          mv output/myPlanet.apk output/myPlanet-${{ env.ANDROID_VERSION_NAME }}-${GITHUB_REF##*/}.apk
          mv output/myPlanet.apk.sha256 output/myPlanet-${{ env.ANDROID_VERSION_NAME }}-${GITHUB_REF##*/}.apk.sha256
          mv output/myPlanet.aab output/myPlanet-${{ env.ANDROID_VERSION_NAME }}-${GITHUB_REF##*/}.aab
          mv output/myPlanet.aab.sha256 output/myPlanet-${{ env.ANDROID_VERSION_NAME }}-${GITHUB_REF##*/}.aab.sha256
          ls -alR output

      - name: upload APK/AAB as build artifact
        if: github.ref != 'refs/heads/master'
        uses: actions/upload-artifact@v3
        with:
          name: myPlanet.zip
          path: output/*

      - name: release signed APK and AAB on GitHub
        if: github.ref == 'refs/heads/master'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: output/*
          tag: v${{ env.ANDROID_VERSION_NAME }}
          overwrite: 'true'
          file_glob: 'true'
