name: myPlanet build test

on:
  push:
    branches:
      - '*'
      - '!master'
#  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build: [default, lite]
    env:
      ANDROID_NDK_VERSION: "21.3.6528147"
      BUILD_TOOLS_VERSION: "30.0.2"

    steps:
      - uses: actions/checkout@v4
      - name: diff the code to get lite
        run: |
          if [[ "${{ matrix.build }}" == "lite" ]]; then
            echo "lite"
            ls -al \
              app/build.gradle \
              app/src/main/AndroidManifest.xml \
              app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt \
              app/src/main/java/org/ole/planet/myplanet/base/PermissionActivity.kt \
              app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.java
            sed -i 's/\(versionName "[0-9.]\+\)"/\1-lite"/' app/build.gradle
            cp app/src/main/AndroidManifest.xml.lite app/src/main/AndroidManifest.xml
            cp app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt.lite app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt
            cp app/src/main/java/org/ole/planet/myplanet/base/PermissionActivity.kt.lite app/src/main/java/org/ole/planet/myplanet/base/PermissionActivity.kt
            cp app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.java.lite app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.java
          fi
      - name: setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'
      - name: install NDK
        run: |
          set -x
          echo "ANDROID_HOME is set to: ${ANDROID_HOME}"
          echo "ANDROID_SDK_ROOT is set to: ${ANDROID_SDK_ROOT}"
          echo "ANDROID_NDK_VERSION is set to: ${ANDROID_NDK_VERSION}"
          #SDK_MANAGER_COMMAND=${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;${ANDROID_NDK_VERSION}" --sdk_root=${ANDROID_SDK_ROOT}
          #SDK_MANAGER_COMMAND="${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --list"
          SDK_MANAGER_COMMAND=${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager "ndk;${ANDROID_NDK_VERSION}" --sdk_root=${ANDROID_SDK_ROOT}
          echo "y" | sudo ${SDK_MANAGER_COMMAND} 2>&1
          if [ $? -ne 0 ]; then
              echo "SDK Manager command failed"
              exit 1
          fi
          set +x
          chmod +x ./gradlew
      - name: build debug as test
        run: ./gradlew assembleDebug
