name: myPlanet build test

on:
  push:
    branches:
      - '*'
      - '!master'
#  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build: [default, lite]
    env:
      ANDROID_NDK_VERSION: "21.3.6528147"
      BUILD_TOOLS_VERSION: "34.0.0"

    steps:
      - name: checkout repository code
        uses: actions/checkout@v4

      - name: ensure *.lite also change
        if: matrix.build == 'lite'
        run: |
          git fetch origin master > /dev/null 2>&1
          declare -a main_files=(
            "app/src/main/AndroidManifest.xml"
            "app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt"
            "app/src/main/java/org/ole/planet/myplanet/base/PermissionActivity.kt"
            "app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt"
          )
          declare -a errors=()
          for file1 in "${main_files[@]}"; do
            file2="${file1}.lite"
            changes=$(git diff --name-only HEAD origin/master | grep -E "^($file1|$file2)$")
            if [ -n "$changes" ] && { ! echo "$changes" | grep -q "^$file1$"; } || { ! echo "$changes" | grep -q "^$file2$"; }; then
              errors+=("Error: Both $file1 and $file2 must be changed together.")
            fi
          done
          if [ ${#errors[@]} -gt 0 ]; then
            printf "%s\n" "${errors[@]}"
            exit 1
          fi

      - name: diff the code to get lite
        if: matrix.build == 'lite'
        run: |
          echo "lite"
          ls -al \
            app/build.gradle \
            app/src/main/AndroidManifest.xml \
            app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt \
            app/src/main/java/org/ole/planet/myplanet/base/PermissionActivity.kt \
            app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt
          sed -i 's/\(versionName "[0-9.]\+\)"/\1-lite"/' app/build.gradle
          cp app/src/main/AndroidManifest.xml.lite app/src/main/AndroidManifest.xml
          cp app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt.lite app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt
          cp app/src/main/java/org/ole/planet/myplanet/base/PermissionActivity.kt.lite app/src/main/java/org/ole/planet/myplanet/base/PermissionActivity.kt
          cp app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt.lite app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt

      - name: setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: install NDK
        run: |
          set -x
          echo "ANDROID_HOME is set to: ${ANDROID_HOME}"
          echo "ANDROID_SDK_ROOT is set to: ${ANDROID_SDK_ROOT}"
          echo "ANDROID_NDK_VERSION is set to: ${ANDROID_NDK_VERSION}"
          echo "y" | sudo ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --install "ndk;${ANDROID_NDK_VERSION}" --sdk_root=${ANDROID_SDK_ROOT} 2>&1
          if [ $? -ne 0 ]; then
              echo "SDK Manager command failed"
              exit 1
          fi
          set +x
          chmod +x ./gradlew

      - name: build debug as test
        run: ./gradlew assembleDebug
